// <auto-generated />

using System.CodeDom.Compiler;
using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace GymTracker.Data.Migrations
{
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class InitialIdentityUpdate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InitialIdentityUpdate));
        
        string IMigrationMetadata.Id
        {
            get { return "201502061310048_InitialIdentityUpdate"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
